version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          JAVA_OPTS: -XX:+UseG1GC -Xmx1024m -Xms512m
          # Disable Kotlin compiler daemon - https://discuss.kotlinlang.org/t/solved-disable-kotlin-compiler-process-keepalive/2622
          GRADLE_OPTS: -Dkotlin.compiler.execution.strategy="in-process"

    working_directory: ~/shared-library-example
    steps:
      - checkout
      - run:
          command: |
            mkdir -p build
            find settings.gradle build.gradle gradle -type f -exec sha256sum '{}' \; | tee build/circle-ci-key.txt
          name: Generate Cache Key
      - restore_cache:
          keys:
          - v1-home-cache-{{ checksum "build/circle-ci-key.txt" }}
          - v1-home-cache-

      - run:
          command: |
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -version
            java -XshowSettings:vm -XX:+PrintCommandLineFlags -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -version
            javac -version
          name: Show Java Version

      - run:
          command: ./gradlew build --max-workers 2 --stacktrace --scan
          name: Build

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-home-cache-{{ checksum "build/circle-ci-key.txt" }}
          when: always

      - store_test_results:
          path: ~/shared-library-example/build/test-results/


